forge 'http://forge.enterprisemodules.com'

mod 'puppetlabs-stdlib',             '4.17.1'
mod 'puppetlabs-concat',             '4.0.1'
mod 'enterprisemodules-easy_type',   '2.2.12'
mod 'enterprisemodules-ora_install', '2.1.12'
mod 'enterprisemodules-ora_config',  '2.3.9'
mod 'fiddyspence-sysctl',            '1.1.0'
mod 'saz-limits',                    '2.5.0'
mod 'saz-timezone',                  '3.3.0'
